=== aborg0/hits/ie.tcd.imm.hits.interop/trunk/ie.tcd.imm.hits.interop/src/ie/tcd/imm/hits/knime/interop/interop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
	targetNamespace="http://hits.googlecode.com/svn/ie.tcd.imm.hits.interop/trunk/ie.tcd.imm.hits.interop"
	elementFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://hits.googlecode.com/svn/ie.tcd.imm.hits.interop/trunk/ie.tcd.imm.hits.interop"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="1.0"
	>
	<annotation>
		<appinfo>
			<jxb:globalBindings>
					<!-- jxb:bindings node="//xsi:attribute[@name='column']/xsi:simpleType">
						<jxb:property>
							<jxb:baseType- - >
								<jxb:javaType name="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.ColumnType"
									parseMethod="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.ColumnType.valueOf"
									printMethod="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.ColumnType.name"
								/>
							<!- - /jxb:baseType>
						</jxb:property> 
					</jxb:bindings-->
			</jxb:globalBindings>
		</appinfo>
	</annotation>
	<element name="root">
		<complexType>
			<sequence maxOccurs="1" minOccurs="1">
				<element ref="tns:defaults"></element>
				<element ref="tns:profiles"></element>
			</sequence>
		</complexType>
	</element>

	<element name="defaults">
		<complexType>
			<sequence maxOccurs="unbounded">
				<element ref="tns:default"></element>
			</sequence>
		</complexType>
	</element>

	<element name="profiles">
		<complexType>
			<sequence maxOccurs="unbounded">
				<element ref="tns:profile"></element>
			</sequence>
		</complexType>
	</element>

	<element name="default" >
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute ref="tns:column" use="required"></attribute>
					<attribute ref="tns:input" use="required"></attribute>
					<attribute ref="tns:dialog" use="required"></attribute>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="profile">
		<complexType>
			<sequence maxOccurs="unbounded" minOccurs="0">
				<element ref="tns:value"></element>
			</sequence>
			<attribute ref="tns:name" use="required"></attribute>
			<attribute ref="tns:modifiable" use="required"></attribute>
			<attribute ref="tns:extends" use="optional"></attribute>
			<attribute ref="tns:input" use="required"></attribute>
		</complexType>
	</element>

	<attribute name="column">
		<simpleType>
			<annotation>
				<appinfo>
					<!-- jxb:bindings node="//xsi:attribute[@name='column']/xsi:simpleType"-->
						<!-- jxb:property>
							<jxb:baseType-->
								<jxb:javaType name="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.ColumnType"
									parseMethod="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.ColumnType.valueOf"
									printMethod="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.ColumnType.nameOf"
								/>
							<!-- /jxb:baseType>
						</jxb:property-->
					<!-- /jxb:bindings-->
					<!-- jxb:typesafeEnumClass name="ColumnType">
						<jxb:typesafeEnumMember name="Plate" value="Plate"/>
						<jxb:typesafeEnumMember name="Replicate" value="Replicate"/>
					</jxb:typesafeEnumClass-->
				</appinfo>
			</annotation>
			<restriction base="string">
				<enumeration value="Plate"></enumeration>
				<enumeration value="Replicate"></enumeration>
			</restriction>
		</simpleType>
	</attribute>

	<attribute name="input" type="boolean"></attribute>

	<attribute name="dialog">
		<simpleType>
			<annotation>
				<appinfo>
								<jxb:javaType name="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.DialogType"
									parseMethod="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.DialogType.valueOf"
									printMethod="ie.tcd.imm.hits.knime.interop.BioConverterNodeDialog.DialogType.nameOf"
								/>
				</appinfo>
			</annotation>
		
			<!-- annotation>
				<appinfo>
					<jxb:typesafeEnumClass name="DialogType">
						<jxb:typesafeEnumMember name="group" value="group"/>
						<jxb:typesafeEnumMember name="name" value="name"/>
						<jxb:typesafeEnumMember name="format" value="format"/>
						<jxb:typesafeEnumMember name="type" value="type"/>
					</jxb:typesafeEnumClass>
				</appinfo>
			</annotation-->
			<restriction base="string">
				<enumeration value="group"></enumeration>
				<enumeration value="name"></enumeration>
				<enumeration value="format"></enumeration>
				<enumeration value="type"></enumeration>
			</restriction>
		</simpleType>
	</attribute>



	<element name="value">
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute ref="tns:column"></attribute>
					<attribute ref="tns:dialog"></attribute>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<attribute name="name" type="string"></attribute>

	<attribute name="modifiable" type="boolean"></attribute>

	<attribute name="extends" type="string"></attribute>
</schema>

=== aborg0/hits/ie.tcd.imm.hits.interop/trunk/ie.tcd.imm.hits.interop/src/ie/tcd/imm/hits/knime/interop/interop.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:root
	xmlns:p="http://hits.googlecode.com/svn/ie.tcd.imm.hits.interop/trunk/ie.tcd.imm.hits.interop"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://hits.googlecode.com/svn/ie.tcd.imm.hits.interop/trunk/ie.tcd.imm.hits.interop interop.xsd ">
  <p:defaults>
    <p:default p:column="Plate" p:dialog="group" p:input="true">custom</p:default>
    <p:default p:column="Plate" p:dialog="name" p:input="true">Plate</p:default>
    <p:default p:column="Plate" p:dialog="format" p:input="true">(\d+)</p:default>
    <p:default p:column="Plate" p:dialog="group" p:input="false">custom</p:default>
    <p:default p:column="Plate" p:dialog="name" p:input="false">Plate</p:default>
    <p:default p:column="Plate" p:dialog="format" p:input="false">${Plate}</p:default>
    <p:default p:column="Plate" p:dialog="type" p:input="false">Integer</p:default>
    <p:default p:column="Replicate" p:dialog="group" p:input="true">custom</p:default>
    <p:default p:column="Replicate" p:dialog="name" p:input="true">Replicate</p:default>
    <p:default p:column="Replicate" p:dialog="format" p:input="true">(\d+)</p:default>
    <p:default p:column="Replicate" p:dialog="group" p:input="false">custom</p:default>
    <p:default p:column="Replicate" p:dialog="name" p:input="false">Replicate</p:default>
    <p:default p:column="Replicate" p:dialog="format" p:input="false">${Replicate}</p:default>
    <p:default p:column="Replicate" p:dialog="type" p:input="false">Integer</p:default>
  </p:defaults>
  <p:profiles>
    <p:profile p:name="custom" p:modifiable="true" p:input="true">
      <p:value p:column="Plate" p:dialog="name">Plate</p:value>
      <p:value p:column="Plate" p:dialog="format">(\d+)</p:value>
      <p:value p:column="Replicate" p:dialog="name">Replicate</p:value>
      <p:value p:column="Replicate" p:dialog="format">(\d+)</p:value>
    </p:profile>
    <p:profile p:name="custom" p:modifiable="true" p:input="false">
      <p:value p:column="Plate" p:dialog="name">Plate</p:value>
      <p:value p:column="Plate" p:dialog="format">${Plate}</p:value>
      <p:value p:column="Plate" p:dialog="type">Integer</p:value>
      <p:value p:column="Replicate" p:dialog="name">Replicate</p:value>
      <p:value p:column="Replicate" p:dialog="format">${Replicate}</p:value>
      <p:value p:column="Replicate" p:dialog="type">Integer</p:value>
    </p:profile>
    <p:profile p:name="cellHTS2Input" p:modifiable="false" p:input="true">
      <p:value p:column="Plate" p:dialog="name">Plate</p:value>
      <p:value p:column="Plate" p:dialog="format">(\d+)</p:value>
      <p:value p:column="Replicate" p:dialog="name">Replicate</p:value>
      <p:value p:column="Replicate" p:dialog="format">(\d+)</p:value>
    </p:profile>
    <p:profile p:name="cellHTS2Input" p:modifiable="false" p:input="false">
      <p:value p:column="Plate" p:dialog="name">Plate</p:value>
      <p:value p:column="Plate" p:dialog="format">${Plate}</p:value>
      <p:value p:column="Plate" p:dialog="type">Integer</p:value>
      <p:value p:column="Replicate" p:dialog="name">Replicate</p:value>
      <p:value p:column="Replicate" p:dialog="format">${Replicate}</p:value>
      <p:value p:column="Replicate" p:dialog="type">Integer</p:value>
    </p:profile>
    <p:profile p:name="cellHTS2Output" p:modifiable="false" p:input="true" p:extends="cellHTS2Input">
    </p:profile>
    <p:profile p:name="cellHTS2Output" p:modifiable="false" p:input="false" p:extends="cellHTS2Input">
    </p:profile>
    <p:profile p:name="HCDC" p:modifiable="false" p:input="true">
      <p:value p:column="Plate" p:dialog="name">barcode</p:value>
      <p:value p:column="Plate" p:dialog="format">.*?(\d+)_(?:\d+)$</p:value>
      <p:value p:column="Replicate" p:dialog="name">barcode</p:value>
      <p:value p:column="Replicate" p:dialog="format">(?:[^_])_(\d+)$</p:value>
    </p:profile>
    <p:profile p:name="HCDC" p:modifiable="false" p:input="false">
      <p:value p:column="Plate" p:dialog="name">barcode</p:value>
      <p:value p:column="Plate" p:dialog="format">${Plate}_${Replicate}</p:value>
      <p:value p:column="Plate" p:dialog="type">String</p:value>
      <p:value p:column="Replicate" p:dialog="name">barcode</p:value>
      <p:value p:column="Replicate" p:dialog="format">${Plate}_${Replicate}</p:value>
      <p:value p:column="Replicate" p:dialog="type">String</p:value>
    </p:profile>
  </p:profiles>
</p:root>
